apiVersion: v1
kind: Pod
metadata:
  name: metrics-pod
spec:
  containers:
    - name: metrics-container
      image: ythadhani/test:metrics
    - name: prometheus
      image: prom/prometheus
      args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus/"
        - "--web.listen-address=:8080"
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
        - name: prometheus-storage-volume
          mountPath: /prometheus/
    - name: grafana
      image: grafana/grafana:latest
      ports:
        - name: grafana
          containerPort: 3000
      resources:
        limits:
          memory: "2Gi"
          cpu: "1000m"
        requests:
          memory: "1Gi"
          cpu: "500m"
      volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
          readOnly: false
  volumes:
    - name: prometheus-config-volume
      configMap:
        defaultMode: 420
        name: prometheus-server-conf
    - name: prometheus-storage-volume
      emptyDir: {}
    - name: grafana-storage
      emptyDir: {}
    - name: grafana-datasources
      configMap:
        defaultMode: 420
        name: grafana-datasources